### PR TITLE
Offline Mission Tracking

### PR DESCRIPTION
**Pull request by Hus274**
### Updated
Added support for offline mission tracking. This change creates three statistics objects when a file is uploaded, one for each progression tracker (online, offline, and both). I've defaulted the selection to both as that seems  like the primary use case but it can easily be changed to a different default.

Typescript is totally new to me so it's possible if not likely that some of this is a bit wonky and could be improved, feel free to let me know if anything shows up.

### CODE REVIEW

**Comment by Hus274** [comment]
Saw your email, I'll refactor this to keep the radio buttons in and push a new commit with those changes.

**Comment by Mazzzoni** [comment]
> Saw your email, I'll refactor this to keep the radio buttons in and push a new commit with those changes.

Hahah, sorry I wish I sent it just a bit earlier, thanks a lot for your time, great contribution ! :D

**Comment by Hus274** [comment]
Alright, updated to support each radio button feature (online, offline, both). Let me know if you have any comments.

**Comment by Mazzzoni** [comment]
I changed a bit the implementation so this way we don't have to deal with multiple Statistics objects but only one, within I splitted the missions stats / progressions for each progression type (keeping your merging / get missions stats logic)
This way we can have more granular level for selecting which progression type we want in components (misc stats APM were broken since the stats are not splitted for each mode) and maybe comparing two modes in the futures :)

It's also a bit easier to play around with values this way I believe, let me know if you have feedback :+1:

**Pull request merged**
